repos:
# Check YAML; Fix end of files; Fix trailing whitespace
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
# Python - Reorder Imports
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports
# Python - Code Formatting
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args:
    - --line-length
    - '79'
    - --skip-string-normalization
# Python - Type Checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    additional_dependencies: [types-pyyaml]
# Unit Testing
- repo: local
  hooks:
  - id: tox
    name: Unit Testing
    entry: tox
    additional_dependencies: ["tox"]
    language: python
    pass_filenames: false
    stages: [manual]
