name: Tests
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
          typer \
          blessed \
          pyyaml \
          tox \
          pytest
    - name: Run Tests
      run: tox
