name: GitHub Workflow
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Test using built-in unittest library.
      run: |
        python -m pip install -r requirements.txt
        python -m unittest discover --start-directory tests
