name: GitHub Workflow
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
          typer \
          blessed \
          pyyaml
    - name: Run Tests
      run: |
        python -m unittest discover --start-directory tests
