name: GitHub Workflow
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
          typer \
          blessed \
          pyyaml \
          pytest
    - name: Run Tests
      run: |
        pytest
