name: GitHub Workflow
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        python -m unittest discover --start-directory tests
